In [1]:
3*5

15

In [2]:
6*55

330

In [4]:
10*'rtt'

'rttrttrttrttrttrttrttrttrttrtt'

In [5]:
type(3)

int

In [6]:
type("rtt")

str

In [8]:
type(True)

bool

In [9]:
a=12
b=13

print(a*b)

156


In [10]:
print(a/b)

0.9230769230769231


In [14]:
my_str="rupesh12"
my_str.isalnum()

True

In [16]:
list=["mathematics","physics",33,33,44,22]
print(list)

['mathematics', 'physics', 33, 44, 22]


In [17]:
list[3]

44

In [20]:
list[0:4]

['mathematics', 'physics', 33, 44]

In [25]:
list.count(33)

1

In [26]:
list.count(33)

1

In [28]:
set_var={2,3,34,4,3}
print(set_var)

{2, 3, 34, 4}


In [33]:
set_var.add('ram')

In [32]:
print(set_var)

{2, 3, 34, 4, 'ram'}


In [35]:
set1={34,44,33,22,33,44}
set2={34,44,33,45,22,33}
set2.difference(set1)

{45}

In [39]:
my_dict={"car1":"bmw","car2":"audi","car3":"maruti"}
my_dict["car2"]

'audi'

In [41]:
for x in my_dict.values():
    print(x)


bmw
audi
maruti


In [46]:
car_mode1={"car1":"bmw"}
car_model2={"car2":"audi"}
car_model3={"car3":"suzuki"}
car_type={"car1":car_mode1,"car2":car_model2,"car3":car_model3}
print(car_type)

{'car1': {'car1': 'bmw'}, 'car2': {'car2': 'audi'}, 'car3': {'car3': 'suzuki'}}


In [51]:
import numpy as np

In [53]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)
print(arr)

[1 2 3 4 5]


In [54]:
import pandas as pd

In [58]:
arr=np.array([2,3,4,5,6,3])
print(arr)

[2 3 4 5 6 3]


In [60]:
arr.shape

(6,)

In [64]:
list_arr=np.array([[2,3,4],[3,4,5,],[2,3,3]])
print(list_arr)

[[2 3 4]
 [3 4 5]
 [2 3 3]]


In [65]:
list_arr.shape

(3, 3)

In [66]:
list_arr.size


9

In [67]:
range=np.arange(12)
print(range)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [69]:
lspace=np.linspace(1,5,4)

In [72]:
print(lspace)

[1. 5.]


In [73]:
arrange=np.arange(34)
arrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [75]:
arrange.reshape(2,17)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33]])

In [76]:
x=[[2,3,4],[23,4,5],[23,44,55]]
arr=np.array(x)
arr

array([[ 2,  3,  4],
       [23,  4,  5],
       [23, 44, 55]])

In [78]:
arr.sum(axis=0)

array([48, 51, 64])

In [80]:
arr.sum(axis=1)

array([  9,  32, 122])

In [81]:
arr.T

array([[ 2, 23, 23],
       [ 3,  4, 44],
       [ 4,  5, 55]])

In [83]:
arr.argmax()

8

In [84]:
dict1={"name":["ram",'shyam',"rohan"],"marks":[34,56,76]
      }
x1=pd.DataFrame(dict1)

In [85]:
x1

name  marks
0    ram     34
1  shyam     56
2  rohan     76

In [87]:
x1.to_csv("nii")


In [91]:
x1.tail(1)

name  marks
2  rohan     76

In [92]:
x1.describe()

marks
count   3.000000
mean   55.333333
std    21.007935
min    34.000000
25%    45.000000
50%    56.000000
75%    66.000000
max    76.000000